name: petkeeper_lite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.0.dev
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  google_sign_in: ^7.2.0
  flutter_riverpod: ^3.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  firebase_app_check: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
